import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export interface ChecklistResult {
  stepNumber: number;
  title: string;
  passed: boolean;
  completedAt: string | null;
}

export interface ReportData {
  operatorFirstName: string;
  operatorLastName: string;
  deviceName: string;
  oldSerialNumber: string;
  newSerialNumber: string;
  firmwareVersion: string;
  completionDateTime: string;
  completionLocation: string;
  checklist: ChecklistResult[];
}

function statusIcon(passed: boolean): string {
  return passed
    ? '<span style="color:#34C759;font-weight:bold;">PASS</span>'
    : '<span style="color:#FF3B30;font-weight:bold;">FAIL</span>';
}

export async function generateReport(data: ReportData): Promise<void> {
  const checklistRows = data.checklist
    .map(
      (item) => `
      <tr>
        <td style="padding:8px;border:1px solid #ddd;">${item.stepNumber}</td>
        <td style="padding:8px;border:1px solid #ddd;">${item.title}</td>
        <td style="padding:8px;border:1px solid #ddd;text-align:center;">${statusIcon(item.passed)}</td>
        <td style="padding:8px;border:1px solid #ddd;">${item.completedAt || "N/A"}</td>
      </tr>`
    )
    .join("");

  const allPassed = data.checklist.every((c) => c.passed);

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        h1 { color: #1a1a1a; border-bottom: 2px solid #34C759; padding-bottom: 10px; }
        h2 { color: #555; margin-top: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #f5f5f5; padding: 10px; border: 1px solid #ddd; text-align: left; }
        .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 15px 0; }
        .info-item { padding: 8px; background: #f9f9f9; border-radius: 4px; }
        .info-label { font-weight: bold; color: #666; font-size: 12px; }
        .info-value { font-size: 14px; margin-top: 4px; }
        .overall { padding: 15px; margin-top: 20px; border-radius: 8px; text-align: center; font-size: 18px; font-weight: bold; }
        .pass { background: #d4edda; color: #155724; }
        .fail { background: #f8d7da; color: #721c24; }
        .footer { margin-top: 40px; text-align: center; color: #999; font-size: 11px; }
      </style>
    </head>
    <body>
      <h1>Blade Factory Test Report</h1>

      <div class="info-grid">
        <div class="info-item">
          <div class="info-label">Operator</div>
          <div class="info-value">${data.operatorFirstName} ${data.operatorLastName}</div>
        </div>
        <div class="info-item">
          <div class="info-label">Device</div>
          <div class="info-value">${data.deviceName}</div>
        </div>
        <div class="info-item">
          <div class="info-label">Old Serial Number</div>
          <div class="info-value">${data.oldSerialNumber || "N/A"}</div>
        </div>
        <div class="info-item">
          <div class="info-label">New Serial Number</div>
          <div class="info-value">${data.newSerialNumber}</div>
        </div>
        <div class="info-item">
          <div class="info-label">Firmware Version</div>
          <div class="info-value">${data.firmwareVersion}</div>
        </div>
        <div class="info-item">
          <div class="info-label">Completion Date/Time</div>
          <div class="info-value">${data.completionDateTime}</div>
        </div>
        <div class="info-item">
          <div class="info-label">Location</div>
          <div class="info-value">${data.completionLocation}</div>
        </div>
      </div>

      <h2>Test Checklist</h2>
      <table>
        <thead>
          <tr>
            <th style="width:40px;">#</th>
            <th>Test</th>
            <th style="width:80px;text-align:center;">Status</th>
            <th style="width:180px;">Completed At</th>
          </tr>
        </thead>
        <tbody>
          ${checklistRows}
        </tbody>
      </table>

      <div class="overall ${allPassed ? "pass" : "fail"}">
        Overall Result: ${allPassed ? "ALL TESTS PASSED" : "SOME TESTS FAILED"}
      </div>

      <div class="footer">
        Generated by Blade Factory App | ${new Date().toISOString()}
      </div>
    </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "Share Factory Test Report",
      UTI: "com.adobe.pdf",
    });
  }
}
