import { Platform } from "react-native";

export const BladeColors = {
  primary: "#0A4D6E",
  primaryDark: "#063549",
  primaryLight: "#0E6B96",
  accent: "#A4D08B",
  accentDark: "#8BC070",
  marine: "#00B8A9",
  warning: "#F59E0B",
  error: "#DC2626",
  success: "#A4D08B",
  live: "#00B8A9",
  offline: "#596F7C",
  gold: "#D4A853",
  platinum: "#B8C4CE",
  white: "#EBEFF3",
  lightGray: "#596F7C",
  darkGray: "#181F27",
};

export const Colors = {
  light: {
    text: BladeColors.darkGray,
    textSecondary: BladeColors.lightGray,
    textTertiary: "#94A3B8",
    buttonText: "#FFFFFF",
    tabIconDefault: BladeColors.lightGray,
    tabIconSelected: BladeColors.primary,
    link: BladeColors.primary,
    backgroundRoot: BladeColors.white,
    backgroundDefault: "#FFFFFF",
    backgroundSecondary: BladeColors.white,
    backgroundTertiary: "#E2E8F0",
    primary: BladeColors.primary,
    primaryDark: BladeColors.primaryDark,
    accent: BladeColors.accent,
    marine: BladeColors.marine,
    warning: BladeColors.warning,
    error: BladeColors.error,
    success: BladeColors.success,
    border: "#E2E8F0",
    borderLight: BladeColors.white,
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    live: BladeColors.live,
    offline: BladeColors.offline,
    cardGradientStart: "#FFFFFF",
    cardGradientEnd: BladeColors.white,
    shimmer: "#E2E8F0",
  },
  dark: {
    text: "#F8FAFC",
    textSecondary: "#94A3B8",
    textTertiary: "#64748B",
    buttonText: "#FFFFFF",
    tabIconDefault: "#64748B",
    tabIconSelected: BladeColors.accent,
    link: BladeColors.accent,
    backgroundRoot: "#0B1120",
    backgroundDefault: "#111827",
    backgroundSecondary: "#1E293B",
    backgroundTertiary: "#334155",
    primary: BladeColors.primaryLight,
    primaryDark: BladeColors.primary,
    accent: BladeColors.accent,
    marine: BladeColors.marine,
    warning: BladeColors.warning,
    error: BladeColors.error,
    success: BladeColors.success,
    border: "#1E293B",
    borderLight: "#334155",
    surface: "#111827",
    surfaceElevated: "#1E293B",
    live: BladeColors.live,
    offline: "#475569",
    cardGradientStart: "#1E293B",
    cardGradientEnd: "#111827",
    shimmer: "#334155",
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  "6xl": 64,
  inputHeight: 52,
  buttonHeight: 56,
  cardPadding: 20,
  screenPadding: 20,
  metricCardSize: 160,
  fabSize: 60,
  fabOffset: 20,
  touchTarget: 48,
};

export const BorderRadius = {
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  "2xl": 28,
  "3xl": 32,
  full: 9999,
};

export const Typography = {
  sizes: {
    xs: 10,
    sm: 12,
    md: 14,
    lg: 16,
    xl: 20,
    "2xl": 24,
    "3xl": 32,
    "4xl": 40,
  },
  hero: {
    fontSize: 44,
    lineHeight: 52,
    fontWeight: "700" as const,
    letterSpacing: -1,
  },
  h1: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: "700" as const,
    letterSpacing: -0.5,
  },
  h2: {
    fontSize: 22,
    lineHeight: 30,
    fontWeight: "600" as const,
    letterSpacing: -0.3,
  },
  h3: {
    fontSize: 18,
    lineHeight: 26,
    fontWeight: "600" as const,
  },
  h4: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "600" as const,
  },
  body: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "400" as const,
  },
  small: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "400" as const,
  },
  caption: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500" as const,
    letterSpacing: 0.5,
  },
  button: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "600" as const,
    letterSpacing: 0.3,
  },
  link: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: "500" as const,
  },
  mono: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500" as const,
  },
  metric: {
    fontSize: 36,
    lineHeight: 44,
    fontWeight: "700" as const,
    letterSpacing: -1,
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "Inter, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});

export const Shadows = {
  none: {
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  subtle: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  small: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  medium: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  large: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 5,
  },
  premium: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 28,
    elevation: 6,
  },
  glow: {
    shadowColor: BladeColors.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 4,
  },
  glowMarine: {
    shadowColor: BladeColors.marine,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  fab: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  card: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 4,
  },
};

export const Gradients = {
  primary: ["#0A4D6E", "#063549"],
  primarySubtle: ["#0E6B96", "#0A4D6E"],
  accent: ["#B5DC9E", "#A4D08B"],
  accentSubtle: ["#A4D08B20", "#A4D08B05"],
  marine: ["#00D4C4", "#00B8A9"],
  marineSubtle: ["#00B8A920", "#00B8A905"],
  dark: ["#1E293B", "#0B1120"],
  card: ["rgba(255,255,255,0.95)", "rgba(255,255,255,0.85)"],
  cardDark: ["#1A2530", "#141C24"],
  cardPremium: ["#1E2832", "#151B23"],
  cardHeader: ["#0A4D6E", "#063549"],
  surface: ["#181F27", "#12181F"],
  overlay: ["rgba(0,0,0,0)", "rgba(0,0,0,0.6)"],
};
